[package]
name = "oauth2"
version = "0.0.1"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
axum = "0.8.9"
base64-url = "3.0.4"
chrono = { version = "0.4.45", features = ["serde"] }
rand = "0.10.2"
reqwest = { version = "0.13.4", features = ["blocking", "form", "json"] }
serde = { version = "1.0.229", features = ["derive"] }
sha2 = "0.11.0"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
